services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"
    restart: unless-stopped
    networks:
      - app-network


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE=http://server:4000
    ports:
      - "5173:4173"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
